version: "3.8"

services:
  # Backend Service (Node.js)
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=db 
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - API_KEY=${API_KEY}
    depends_on:
      - db 
    volumes:
      - ./server:/app 
      - /app/node_modules 

  # Frontend Service (React)
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  # Database Service (PostgreSQL)
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: 
